### ISSUE TITLE
unlockWithCodeEnabled:FALSE does not respect a unlock context

### ISSUE THREAD

**Issue by bushe** [bd452/libPassword#8]
unlockWithCodeEnabled:False does not respect a unlock context that has been set in SBLockScreenViewController.

Things like notifications set an unlock context within the SBLockScreenViewController to launch to the app when unlocking with them. When manually setting a unlock context and  using unlockWithCodeEnabled:FALSE libPassword disregards the unlock context. I have found a work around by using setPasscodeToggle:FALSE and then calling;
[[[SBLockScreenManager sharedInstance] lockScreenViewController] passcodeLockViewPasscodeEntered:nil]

It would be nice to have the fixed or added in libPassword.

**Comment by efrederickson** [comment]
Fixed (and verified) using the supplied code you recommended.
